site_name: M365 Security Alerts to Teams
repo_name: berkeleyo/m365-security-alerts-to-teams
repo_url: https://github.com/berkeleyo/m365-security-alerts-to-teams

theme:
  name: material
  features:
    - navigation.sections
    - toc.integrate
    - content.code.copy

nav:
  - Home: docs/index.md
  - Deploy: docs/DEPLOY.md
  - Operations: docs/OPERATIONS.md
  - Troubleshooting: docs/TROUBLESHOOTING.md
  - FAQ: docs/FAQ.md
